# Generated by Django 5.2.4 on 2025-07-25 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_alter_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
