# Generated by Django 5.2.4 on 2025-07-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_coursestudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStudent',
        ),
    ]
