# Generated by Django 5.2.5 on 2025-08-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_alter_group_students_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
